documentation: Point README to developer guide
aws/amazon-braket-sdk-python pull request #179
Opened 2020-12-02 22:35 UTC by speller26

Instead of listing available devices, the README now links to the Amazon
Braket developer guide. The prevents the need to change the README with
each new device.

Also changed the bucket used in examples from amazon-braket-output-<ID>
to amazon-braket-<ID>, the correct default bucket name.

*Issue #, if available:*

*Description of changes:*

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-sdk-python/blob/main/README.md) and [API docs](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-12-02 22:51 UTC, wrasmuss commented on README.md
> +- The fully managed simulators offer high performance circuit simulations, and can handle larger circuits than can be run on user hardware. For example, the SV1 state vector simulator used in the abo
```suggestion
- The fully managed simulators offer high performance circuit simulations, and can handle larger circuits than can be run on user hardware. For example, the SV1 state vector simulator used in the above examples will take approximately 1-2 hours to complete to run a 34-qubit, dense, and square (circuit depth = 34) circuit, depending on the type of gates used and other factors. For a list of available simulators and their features, consult the Amazon Braket [developer guide full device list](https://docs.aws.amazon.com/braket/latest/developerguide/braket-devices.html).
```

2020-12-02 22:52 UTC, wrasmuss reviewed
See single suggestion

2020-12-02 23:07 UTC, lundql requested changes

2020-12-02 23:07 UTC, lundql commented on README.md
> +Specify which quantum hardware device to use by specifying its ARN as the value of the `device_arn` argument. A list of all available quantum devices and their features can be found in the Amazon Bra
To select a quantum hardware device, specify its ARN as the value of the `device_arn` argument. A list of available quantum devices and their features can be found in the [Amazon Braket Developer Guide](https://docs.aws.amazon.com/braket/latest/developerguide/braket-devices.html).

(Note to writer: The actual title of the document is as shown. Other edits for clarity and grammar.)

2020-12-02 23:14 UTC, speller26 commented on README.md
> +Two types of circuit simulators are available: fully managed simulators accessed through the Amazon Braket service, and a local simulator bundled with the Amazon Braket SDK.
The following long descriptions are also bulleted; how should they be arranged relative to these bullets?

2020-12-02 23:37 UTC, lundql commented on README.md
> +Two types of circuit simulators are available: fully managed simulators accessed through the Amazon Braket service, and a local simulator bundled with the Amazon Braket SDK.
I edited the previous comment per your question

2020-12-03 00:23 UTC, lundql approved these changes

2020-12-03 00:25 UTC, merged