[WIP] Feature/ahs local sim
aws/amazon-braket-sdk-python pull request #451
Opened 2022-09-23 21:40 UTC by maolinml

*Issue #, if available:*
Allow neutral atom simulator to run at the SDK level

*Description of changes:*
Allow local simulator to run AnalogHamiltonianSimulation. Related PR. 

*Testing done:*
The example notebooks can be run successfully. The unit tests are not added yet, this is WIP. 

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md) doc
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-sdk-python/blob/main/README.md) and [API docs](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-23 22:04 UTC, peterkomar-aws requested changes

2022-09-23 22:04 UTC, peterkomar-aws commented on setup.py
> +        "amazon-braket-default-simulator",
I understand that it's convenient for you to have this in your local copy, but there is no reason to commit it. Please reverse it in the PR.

2022-09-23 22:12 UTC, krneta approved these changes

2022-09-30 19:23 UTC, peterkomar-aws approved these changes

2022-09-30 19:24 UTC, merged